# Generated by Django 3.2.16 on 2024-04-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240429_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bloodgroup'),
        ),
    ]
