# Generated by Django 3.2.16 on 2024-04-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
    ]
