# Generated by Django 3.2.16 on 2024-04-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240429_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('symble', models.TextField()),
                ('image', models.ImageField(upload_to='images/blood')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bloodgroup'),
        ),
    ]
