# Generated by Django 3.2.16 on 2024-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_profile_setup_profile_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iamge',
            field=models.FileField(upload_to='images/profiles'),
        ),
    ]
