# Generated by Django 3.2.16 on 2024-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_iamge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iamge',
            field=models.FileField(default='images/profiles/profile.png', upload_to='images/profiles'),
        ),
    ]
