# Generated by Django 3.2.16 on 2024-05-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodgroup',
            old_name='symble',
            new_name='symbol',
        ),
    ]
