# Generated by Django 3.2.16 on 2024-05-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_symble_bloodgroup_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iamge',
            new_name='image',
        ),
    ]
