# Generated by Django 3.2.16 on 2024-05-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_under_review_profile_is_under_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upazila',
            old_name='discrict',
            new_name='district',
        ),
    ]
