# Generated by Django 3.2.16 on 2024-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_donation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
