# Generated by Django 3.2.16 on 2024-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_profile_last_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
