# Generated by Django 3.2.16 on 2024-05-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_donationaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentNubmersZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='UrgentNubmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('number', models.TextField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.urgentnubmerszone')),
            ],
        ),
    ]
