# Generated by Django 3.2.16 on 2024-05-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_urgentnubmers_urgentnubmerszone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrgentNubmers',
            new_name='UrgentNubmer',
        ),
    ]
