# Generated by Django 3.2.16 on 2024-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='fotterText',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
