# Generated by Django 3.2.16 on 2024-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_fottertext_homepage_footertext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footerText',
            new_name='footer_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='headerText',
            new_name='header_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
