# Generated by Django 3.2.16 on 2024-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='images/profiles/profile.png', upload_to='images/profiles'),
        ),
    ]
