# Generated by Django 3.2.16 on 2024-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDonnerReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
