# Generated by Django 3.2.16 on 2024-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_nondonnerreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=10000)),
                ('is_smtp', models.BooleanField(default=False)),
                ('smtp_server', models.CharField(max_length=10000)),
                ('smtp_password', models.CharField(max_length=10000)),
                ('smtp_port', models.CharField(max_length=10000)),
            ],
        ),
    ]
