# Generated by Django 3.2.16 on 2024-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_notificationmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmail',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmail',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmail',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
